version: '3.8'

services:

  postgres:
    image: postgres:14.2
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"